"""Added user user table

Revision ID: a7513d2aecc9
Revises: a0ee9cefbbbb
Create Date: 2021-09-18 12:05:00.017134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7513d2aecc9'
down_revision = 'a0ee9cefbbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
